#!/bin/bash

# cleanup
rm -rf obj_dir
rm -f f1.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
# 注意：这里列出了所有需要的 .sv 文件，包括顶层和所有子模块
verilator -Wall --cc --trace f1.sv clktick.sv delay.sv lfsr7.sv f1_fsm.sv mux2.sv --exe f1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1.mk Vf1

# run executable simulation file
obj_dir/Vf1
